name: fvm
description: A simple cli to manage Flutter SDK versions per project. Support
  channels, releases, and local cache for fast switching between versions.
version: 2.4.1
homepage: https://github.com/leoafarias/fvm

environment:
  sdk: ">=2.19.1 <3.0.0"

executables:
  fvm: main

dependencies:
  args: ^2.3.1
  cli_notify: ^0.0.4
  cli_util: ^0.3.5
  console: ^4.1.0
  date_format: ^2.0.6
  io: ^1.0.3
  meta: ^1.8.0
  path: ^1.8.2
  process_run: ^0.12.3+2
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.1.11
  build_version: ^2.1.1
  effective_dart: ^1.3.2
  cli_pkg: ^2.1.4

  grinder: ^0.9.2
  test: ^1.21.3
  build_test: ^2.1.5
  test_cov: ^1.0.1
