name: "Prepare"
description: "Prepare and tests the project"

inputs:
  sdk-version:
    description: "Dart SDK version"
    required: false
    # 3.1.3 Version tested and within the compatibility
    default: "3.1.3"

runs:
  using: "composite"
  steps:
  
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ inputs.sdk-version }} 

    - name: Get dependencies
      run: dart pub get
      shell: bash

    - name: Install DCM
      uses: CQLabs/setup-dcm@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run DCM
      uses: CQLabs/dcm-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        folders: lib
