name: Deploy Homebrew

on:
    workflow_dispatch:

jobs:
    deploy-homebrew:
        name: Update Homebrew
        runs-on: macos-latest
        env:
            PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
            GITHUB_TOKEN: ${{ secrets.HOMEBREW_FVM_GH_TOKEN }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4
  
          - name: Prepare environment
            uses: ./.github/actions/prepare

          - name: Build version and env
            run: dart run grinder build-version --deploy-type=brew

          - name: Deploy homebrew
            run: dart run grinder pkg-homebrew-update


            
