name: Deploy Macos

on:
    workflow_dispatch:

jobs:
    deploy-macos:
        name: Deploy (Macos)
        runs-on: macos-latest
        env:
            PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Prepare environment
          uses: ./.github/actions/prepare

        - name: Build version and env
          run: dart run grinder build-version --deploy-type=brew

        - name: Deploy Github Mac
          run: dart run grinder pkg-github-macos
          