name: Deploy Windows

on:  
    workflow_dispatch:

jobs:
    deploy-windows:
        name: Deploy (Windows)
        runs-on: windows-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHOCOLATEY_TOKEN: ${{ secrets.CHOCOLATEY_TOKEN }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: Prepare environment
            uses: ./.github/actions/prepare

          - name: Build version and env
            run: dart run grinder build-version --deploy-type=chocolatey
    
          - name: Deploy Github Windows
            run: dart run grinder pkg-github-windows
    
          - name: Deploy Chocolatey (Windows)
            run: dart run grinder pkg-chocolatey-deploy