name: Test CLI

on:
  workflow_call:
    inputs:
      sdk-version:
        description: "Dart SDK version"
        type: string
        required: false
        default: "3.1.3"

  pull_request:
    paths-ignore:
      - "website/**"
      - "README.md"
      - "CHANGELOG.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on ${{ matrix.os }}
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare
        with:
          sdk-version: ${{ github.event.inputs.sdk-version }}

      # - name: Install DCM
      #   uses: CQLabs/setup-dcm@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Run DCM
      #   uses: CQLabs/dcm-action@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     folders: lib
  

      - name: Tests
        uses: ./.github/actions/test
        if: matrix.os != 'ubuntu-latest'

      
      - name: Install lcov
        run: sudo apt-get install lcov 
        if: matrix.os == 'ubuntu-latest'

      - name: Run tests
        uses: ./.github/actions/test
        if: matrix.os == 'ubuntu-latest'
        with:
          with-coverage: 'true'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}