name: Test CLI

on: [pull_request]

jobs:
  test_cli:
    name: "${{ matrix.sdk-version }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, windows-2019, ubuntu-18.04]
        sdk-version: [stable] #, dev]
        include:
          - os: macOS-10.14
            TARGET: macos
          - os: ubuntu-18.04
            TARGET: linux
          - os: windows-2019
            TARGET: windows

    steps:
      - uses: actions/checkout@v1

      - name: Setup Dart ${{ matrix.dart-version }}
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: ${{ matrix.sdk-version }}

      - name: Setup Flutter ${{ matrix.sdk-version }}
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: ${{ matrix.sdk-version }}

      - name: Install dependencies
        run: pub get
        working-directory: packages/cli
      - name: Run tests
        run: pub run test
        working-directory: packages/cli
      - name: Static Analyzer
        uses: axel-op/dart-package-analyzer@v2
        id: analysis # set an id for the current step
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: packages/cli

        # You can then use this id to retrieve the outputs in the next steps.
        # The following step shows how to exit the workflow with an error if a score is below 100:
      - name: Score below 100.0
        # NB: "analysis" is the id set above. Replace it with the one you used if different.
        if: ${{ (steps.analysis.outputs.maintenance != 100.0) || (steps.analysis.outputs.health != 100)}}
        run: exit 1
